/**
 * L2 Model: 稳定诊断代码目录。
 *
 * 代码是可观察输出的一部分（Requirements 13.2），一经使用不得改写含义。
 * 需求文档显式点名的代码类别（`LAYER_L1_OWNERSHIP`、`LAYER_L3_OWNERSHIP`、
 * `VALUE_L3_OWNERSHIP`、`LAYER_L1_RUNTIME_STATE`）使用与需求完全一致的字符串。
 */

export const DIAGNOSTIC_CODES = {
  // ── 来源裁决与追踪（Requirements 1、16） ──────────────────────────────
  SOURCE_DISPLACED_BY_HIGHER_PRECEDENCE: 'SOURCE_DISPLACED_BY_HIGHER_PRECEDENCE',
  SOURCE_SAME_PRECEDENCE_CONFLICT: 'SOURCE_SAME_PRECEDENCE_CONFLICT',
  SOURCE_DECISION_ID_REUSE: 'SOURCE_DECISION_ID_REUSE',
  SOURCE_CONTRACT_WITHHELD: 'SOURCE_CONTRACT_WITHHELD',
  SOURCE_MISSING_AUTHORITATIVE_RECORD: 'SOURCE_MISSING_AUTHORITATIVE_RECORD',
  SOURCE_MARKER_BLOCKS_DEFAULT: 'SOURCE_MARKER_BLOCKS_DEFAULT',
  SOURCE_DEPRECATED_MECHANIC: 'SOURCE_DEPRECATED_MECHANIC',
  SOURCE_PRESENTATION_ONLY_EXCLUDED: 'SOURCE_PRESENTATION_ONLY_EXCLUDED',
  SOURCE_GAMEPLAY_COUPLED_TO_L3: 'SOURCE_GAMEPLAY_COUPLED_TO_L3',
  SOURCE_UNRESOLVED_ITEM_RETAINED: 'SOURCE_UNRESOLVED_ITEM_RETAINED',
  SOURCE_CLASSIFICATION_MISMATCH: 'SOURCE_CLASSIFICATION_MISMATCH',
  SOURCE_UNSUPPORTED_NORMATIVE_CONSTANT: 'SOURCE_UNSUPPORTED_NORMATIVE_CONSTANT',
  SOURCE_NUMERIC_EXAMPLE_UNCLASSIFIED: 'SOURCE_NUMERIC_EXAMPLE_UNCLASSIFIED',
  SOURCE_PROMOTION_REQUIRES_DECISION: 'SOURCE_PROMOTION_REQUIRES_DECISION',

  // ── 层级归属（Requirements 2、9.8） ───────────────────────────────────
  LAYER_L1_OWNERSHIP: 'LAYER_L1_OWNERSHIP',
  LAYER_L3_OWNERSHIP: 'LAYER_L3_OWNERSHIP',
  LAYER_L1_RUNTIME_STATE: 'LAYER_L1_RUNTIME_STATE',
  VALUE_L3_OWNERSHIP: 'VALUE_L3_OWNERSHIP',

  // ── 术语（Requirements 1.6–1.7） ─────────────────────────────────────
  TERM_DEPRECATED_LAYER_TERM: 'TERM_DEPRECATED_LAYER_TERM',

  // ── 定义形状与标识（Requirements 4） ─────────────────────────────────
  DEF_MISSING_REQUIRED_FIELD: 'DEF_MISSING_REQUIRED_FIELD',
  DEF_MALFORMED_IDENTIFIER: 'DEF_MALFORMED_IDENTIFIER',
  DEF_DUPLICATE_IDENTIFIER: 'DEF_DUPLICATE_IDENTIFIER',
  DEF_INVALID_DEF_KIND: 'DEF_INVALID_DEF_KIND',
  DEF_ABSTRACT_INSTANTIATION: 'DEF_ABSTRACT_INSTANTIATION',
  DEF_INSTANCE_CARRIES_GAMEPLAY_VALUE: 'DEF_INSTANCE_CARRIES_GAMEPLAY_VALUE',
  DEF_INSTANCE_CARRIES_GAMEPLAY_RULE: 'DEF_INSTANCE_CARRIES_GAMEPLAY_RULE',
  DEF_MISSING_SOURCE_RECORD: 'DEF_MISSING_SOURCE_RECORD',

  // ── 语义族登记（Requirements 4.2–4.4） ──────────────────────────────
  FAMILY_NOT_ENUMERABLE: 'FAMILY_NOT_ENUMERABLE',
  FAMILY_NOT_COMPOSABLE: 'FAMILY_NOT_COMPOSABLE',
  FAMILY_GAMEPLAY_DEPENDENT: 'FAMILY_GAMEPLAY_DEPENDENT',
  FAMILY_MISSING_CLASSIFICATION_REASON: 'FAMILY_MISSING_CLASSIFICATION_REASON',
  FAMILY_UNREGISTERED: 'FAMILY_UNREGISTERED',
  FAMILY_DUPLICATE_REGISTRATION: 'FAMILY_DUPLICATE_REGISTRATION',
  FAMILY_COMBINATION_INSTANCE_AS_BASE: 'FAMILY_COMBINATION_INSTANCE_AS_BASE',

  // ── 参数 Schema 与数值（Requirements 5） ────────────────────────────
  SCHEMA_FIELD_MISSING_CLASSIFICATION: 'SCHEMA_FIELD_MISSING_CLASSIFICATION',
  SCHEMA_FIELD_INVALID_TYPE: 'SCHEMA_FIELD_INVALID_TYPE',
  SCHEMA_FIELD_DUPLICATE_NAME: 'SCHEMA_FIELD_DUPLICATE_NAME',
  SCHEMA_FIELD_RANGE_MALFORMED: 'SCHEMA_FIELD_RANGE_MALFORMED',
  SCHEMA_FIELD_REFERENCE_TARGET_MISSING: 'SCHEMA_FIELD_REFERENCE_TARGET_MISSING',
  SCHEMA_CROSS_FIELD_CONSTRAINT_UNRESOLVED: 'SCHEMA_CROSS_FIELD_CONSTRAINT_UNRESOLVED',
  SCHEMA_STRUCTURAL_BOUND_MISSING_SOURCE: 'SCHEMA_STRUCTURAL_BOUND_MISSING_SOURCE',
  SCHEMA_STRUCTURAL_BOUND_MISSING_RATIONALE: 'SCHEMA_STRUCTURAL_BOUND_MISSING_RATIONALE',
  SCHEMA_CONSTITUTIONAL_CONSTANT_MISSING_SOURCE: 'SCHEMA_CONSTITUTIONAL_CONSTANT_MISSING_SOURCE',
  SCHEMA_CONSTITUTIONAL_CONSTANT_MISSING_LAYER: 'SCHEMA_CONSTITUTIONAL_CONSTANT_MISSING_LAYER',
  SCHEMA_GAMEPLAY_VALUE_OUT_OF_RANGE: 'SCHEMA_GAMEPLAY_VALUE_OUT_OF_RANGE',
  SCHEMA_GAMEPLAY_TABLE_IN_L2: 'SCHEMA_GAMEPLAY_TABLE_IN_L2',
  SCHEMA_INTERNAL_METRIC_MISSING_SCHEMA: 'SCHEMA_INTERNAL_METRIC_MISSING_SCHEMA',

  // ── 继承与组合（Requirements 3） ────────────────────────────────────
  INHERIT_NO_TYPE_IDENTITY_DIFFERENCE: 'INHERIT_NO_TYPE_IDENTITY_DIFFERENCE',
  INHERIT_GAMEPLAY_VALUE_ONLY_DIFFERENCE: 'INHERIT_GAMEPLAY_VALUE_ONLY_DIFFERENCE',
  INHERIT_CYCLE: 'INHERIT_CYCLE',
  INHERIT_FIELD_CONFLICT_WITHOUT_RULE: 'INHERIT_FIELD_CONFLICT_WITHOUT_RULE',
  INHERIT_INCOMPATIBLE_FIELD_TYPE: 'INHERIT_INCOMPATIBLE_FIELD_TYPE',
  COMPOSE_DUPLICATE_COMPONENT: 'COMPOSE_DUPLICATE_COMPONENT',
  COMPOSE_ORDER_DEPENDENCY_UNDECLARED: 'COMPOSE_ORDER_DEPENDENCY_UNDECLARED',
  COMPOSE_TYPE_DEFINING_CAPABILITY_REMOVED: 'COMPOSE_TYPE_DEFINING_CAPABILITY_REMOVED',
  COMPOSE_NESTED_UNRESOLVED: 'COMPOSE_NESTED_UNRESOLVED',

  // ── 引用与依赖（Requirements 12） ───────────────────────────────────
  REF_MISSING_TARGET: 'REF_MISSING_TARGET',
  REF_KIND_MISMATCH: 'REF_KIND_MISMATCH',
  REF_FAMILY_MISMATCH: 'REF_FAMILY_MISMATCH',
  REF_ABSTRACT_TARGET: 'REF_ABSTRACT_TARGET',
  REF_DEPENDENCY_CYCLE: 'REF_DEPENDENCY_CYCLE',
  REF_PACKAGE_DEPENDENCY_CYCLE: 'REF_PACKAGE_DEPENDENCY_CYCLE',
  REF_INBOUND_LEFT_DANGLING: 'REF_INBOUND_LEFT_DANGLING',
  REF_OVERRIDE_INVALIDATES_DEPENDENT: 'REF_OVERRIDE_INVALIDATES_DEPENDENT',
  REF_REMOVAL_TARGET_MISSING: 'REF_REMOVAL_TARGET_MISSING',
  REF_OVERRIDE_TARGET_MISSING: 'REF_OVERRIDE_TARGET_MISSING',
  REF_OVERRIDE_NOT_DECLARED: 'REF_OVERRIDE_NOT_DECLARED',

  // ── 动作与网关（Requirements 6） ────────────────────────────────────
  ACTION_MISSING_CONTRACT_FIELD: 'ACTION_MISSING_CONTRACT_FIELD',
  ACTION_MULTI_AP_ATOMIC_COST: 'ACTION_MULTI_AP_ATOMIC_COST',
  ACTION_SEQUENCE_MISSING_INTERMEDIATE_STATUS: 'ACTION_SEQUENCE_MISSING_INTERMEDIATE_STATUS',
  ACTION_ATTACHED_WITHOUT_HOST: 'ACTION_ATTACHED_WITHOUT_HOST',
  ACTION_ATTACHED_AS_DECISION_BRANCH: 'ACTION_ATTACHED_AS_DECISION_BRANCH',
  ACTION_ATTACHED_NONZERO_COST: 'ACTION_ATTACHED_NONZERO_COST',
  GATEWAY_KIND_AMBIGUOUS: 'GATEWAY_KIND_AMBIGUOUS',
  GATEWAY_MISSING_CONTRACT_FIELD: 'GATEWAY_MISSING_CONTRACT_FIELD',
  GATEWAY_NAMED_GAMEPLAY_ENTITY: 'GATEWAY_NAMED_GAMEPLAY_ENTITY',
  GATEWAY_CONCRETE_THRESHOLD: 'GATEWAY_CONCRETE_THRESHOLD',

  // ── 空间（Requirements 7） ──────────────────────────────────────────
  SPACE_SCENE_SCALE_MISSING: 'SPACE_SCENE_SCALE_MISSING',
  SPACE_CONCRETE_MAP_NODE: 'SPACE_CONCRETE_MAP_NODE',
  SPACE_CONNECTION_BOUND_UNSOURCED: 'SPACE_CONNECTION_BOUND_UNSOURCED',
  SPACE_MICRO_SCENE_PARENT_MISSING: 'SPACE_MICRO_SCENE_PARENT_MISSING',
  SPACE_MICRO_SCENE_MULTIPLE_PARENTS: 'SPACE_MICRO_SCENE_MULTIPLE_PARENTS',
  SPACE_MICRO_SCENE_OWNER_SEMANTICS: 'SPACE_MICRO_SCENE_OWNER_SEMANTICS',
  SPACE_CREATOR_MUTABLE: 'SPACE_CREATOR_MUTABLE',
  SPACE_MICRO_SCENE_MISSING_OCCUPANCY: 'SPACE_MICRO_SCENE_MISSING_OCCUPANCY',
  SPACE_SMALL_SCENE_MISSING_SHARED_MICRO_SCENE: 'SPACE_SMALL_SCENE_MISSING_SHARED_MICRO_SCENE',
  SPACE_SMALL_SCENE_PERSONAL_VACANT_GROUND: 'SPACE_SMALL_SCENE_PERSONAL_VACANT_GROUND',
  SPACE_TRANSITION_MISSING_FIELD: 'SPACE_TRANSITION_MISSING_FIELD',
  SPACE_TRANSITION_ENDPOINT_KIND: 'SPACE_TRANSITION_ENDPOINT_KIND',
  SPACE_PARENT_REMOVAL_ORPHANS_CHILD: 'SPACE_PARENT_REMOVAL_ORPHANS_CHILD',
  SPACE_PARENT_REMOVAL_UNSUPPORTED_LIFECYCLE_OP: 'SPACE_PARENT_REMOVAL_UNSUPPORTED_LIFECYCLE_OP',

  // ── 物品、装备与载具（Requirements 8） ──────────────────────────────
  ITEM_MISSING_CONTRACT_FIELD: 'ITEM_MISSING_CONTRACT_FIELD',
  ITEM_DANGLING_CAPABILITY_REFERENCE: 'ITEM_DANGLING_CAPABILITY_REFERENCE',
  ITEM_HEAVY_TAG_NOT_QUERY_BASED: 'ITEM_HEAVY_TAG_NOT_QUERY_BASED',
  ITEM_DEATH_CONTAINER_DEPOSIT_ENABLED: 'ITEM_DEATH_CONTAINER_DEPOSIT_ENABLED',
  ITEM_DEATH_CONTAINER_MISSING_TRANSACTION_SOURCE: 'ITEM_DEATH_CONTAINER_MISSING_TRANSACTION_SOURCE',
  ITEM_DEATH_CONTAINER_TIMING_VIOLATION: 'ITEM_DEATH_CONTAINER_TIMING_VIOLATION',
  WEAPON_TYPE_IDENTITY_MISSING: 'WEAPON_TYPE_IDENTITY_MISSING',
  WEAPON_CONCRETE_DAMAGE_VALUE: 'WEAPON_CONCRETE_DAMAGE_VALUE',
  // 2026-08-08 权威变更：WEAPON_ATTACK_SHAPE_NOT_COMPOSED 已删除（未被任何验证器实际触发）。
  // 攻击形状判定为冗余设计，已被武器属性（散射/扫射/连发）完全覆盖，见
  // src/l2/model/family-contracts.ts 顶部权威变更说明。
  ARMOR_MISSING_MITIGATION_REFERENCE: 'ARMOR_MISSING_MITIGATION_REFERENCE',
  ARMOR_EMBEDDED_CONCRETE_INSTANCE: 'ARMOR_EMBEDDED_CONCRETE_INSTANCE',
  CONSUMABLE_MISSING_CONTRACT_FIELD: 'CONSUMABLE_MISSING_CONTRACT_FIELD',
  VEHICLE_NOT_ENTITY: 'VEHICLE_NOT_ENTITY',
  VEHICLE_MISSING_CAPABILITY: 'VEHICLE_MISSING_CAPABILITY',
  VEHICLE_DOOR_IDENTIFIER_UNSTABLE: 'VEHICLE_DOOR_IDENTIFIER_UNSTABLE',
  VEHICLE_ADJACENCY_COUPLED_TO_DOOR_TARGET: 'VEHICLE_ADJACENCY_COUPLED_TO_DOOR_TARGET',
  VEHICLE_D030_POLICY_NOT_L3: 'VEHICLE_D030_POLICY_NOT_L3',

  // ── 效果类与 AI（Requirements 9、10） ───────────────────────────────
  DAMAGE_ASSIGNS_AMOUNT: 'DAMAGE_ASSIGNS_AMOUNT',
  DAMAGE_MISSING_CONTRACT_FIELD: 'DAMAGE_MISSING_CONTRACT_FIELD',
  STATUS_MISSING_CONTRACT_FIELD: 'STATUS_MISSING_CONTRACT_FIELD',
  STATUS_INTERACTION_WITHOUT_RULE: 'STATUS_INTERACTION_WITHOUT_RULE',
  STATUS_PSEUDO_SUBTYPE: 'STATUS_PSEUDO_SUBTYPE',
  SKILL_ACTIVATION_SEMANTICS_MISSING: 'SKILL_ACTIVATION_SEMANTICS_MISSING',
  SKILL_MISSING_CONTRACT_FIELD: 'SKILL_MISSING_CONTRACT_FIELD',
  MOVEMENT_TRAVERSAL_SEMANTICS_MISSING: 'MOVEMENT_TRAVERSAL_SEMANTICS_MISSING',
  MOVEMENT_PARAMETER_NOT_L3_OWNED: 'MOVEMENT_PARAMETER_NOT_L3_OWNED',
  ATTACHMENT_MISSING_CONTRACT_FIELD: 'ATTACHMENT_MISSING_CONTRACT_FIELD',
  AI_MISSING_CONTRACT_FIELD: 'AI_MISSING_CONTRACT_FIELD',
  AI_POLICY_CATEGORY_MISMATCH: 'AI_POLICY_CATEGORY_MISMATCH',
  AI_EMBEDDED_GAMEPLAY_DETAIL: 'AI_EMBEDDED_GAMEPLAY_DETAIL',
  AI_REQUIRED_ACTION_SET_EMPTY: 'AI_REQUIRED_ACTION_SET_EMPTY',
  AI_REQUIRED_TAG_UNRESOLVED: 'AI_REQUIRED_TAG_UNRESOLVED',
  AI_EVALUATION_INVALID: 'AI_EVALUATION_INVALID',
  AI_REDEFINES_L1_INTERFACE: 'AI_REDEFINES_L1_INTERFACE',

  // ── JSON Codec 与 UGC（Requirements 11） ───────────────────────────
  JSON_PARSE_ERROR: 'JSON_PARSE_ERROR',
  JSON_SCHEMA_VERSION_MISSING: 'JSON_SCHEMA_VERSION_MISSING',
  JSON_SCHEMA_VERSION_UNSUPPORTED: 'JSON_SCHEMA_VERSION_UNSUPPORTED',
  JSON_PROHIBITED_CONSTRUCT: 'JSON_PROHIBITED_CONSTRUCT',
  JSON_ROOT_NOT_OBJECT: 'JSON_ROOT_NOT_OBJECT',
  JSON_SEMANTIC_FIELD_MISSING: 'JSON_SEMANTIC_FIELD_MISSING',
  JSON_SEMANTIC_FIELD_DAMAGED: 'JSON_SEMANTIC_FIELD_DAMAGED',
  JSON_NON_FINITE_NUMBER: 'JSON_NON_FINITE_NUMBER',
  PRESENTATION_FALLBACK_APPLIED: 'PRESENTATION_FALLBACK_APPLIED',
  UGC_EXECUTABLE_OUTPUT: 'UGC_EXECUTABLE_OUTPUT',
  UGC_SEMANTIC_GUESS_REJECTED: 'UGC_SEMANTIC_GUESS_REJECTED',

  // ── 包与激活（Requirements 12、13） ────────────────────────────────
  PKG_MISSING_METADATA: 'PKG_MISSING_METADATA',
  PKG_DEPENDENCY_MISSING: 'PKG_DEPENDENCY_MISSING',
  PKG_ACTIVATION_ABORTED: 'PKG_ACTIVATION_ABORTED',
  PKG_SILENT_COERCION_PROPOSAL: 'PKG_SILENT_COERCION_PROPOSAL',
  PKG_REJECTION_WITHOUT_ERROR: 'PKG_REJECTION_WITHOUT_ERROR',

  // ── 空间与物品特定规则（PT-08b） ─────────────────────────────────────
  UNRESOLVED_ITEM_PROMOTION_ATTEMPT: 'UNRESOLVED_ITEM_PROMOTION_ATTEMPT',
  D016_REMOVED_STATUS_REFERENCE: 'D016_REMOVED_STATUS_REFERENCE',
  OP_BYPASS_FORBIDDEN: 'OP_BYPASS_FORBIDDEN',
  SCENE_SCALE_INVALID: 'SCENE_SCALE_INVALID',
  SCENE_MISSING_REQUIRED_CAPABILITY: 'SCENE_MISSING_REQUIRED_CAPABILITY',
  MICRO_SCENE_CREATOR_MISUSE: 'MICRO_SCENE_CREATOR_MISUSE',
  MICRO_SCENE_OCCUPANCY_SOURCE_INVALID: 'MICRO_SCENE_OCCUPANCY_SOURCE_INVALID',
  VEHICLE_NOT_MICRO_SCENE: 'VEHICLE_NOT_MICRO_SCENE',
  TRANSITION_ENDPOINT_TYPE_INVALID: 'TRANSITION_ENDPOINT_TYPE_INVALID',
  TRANSITION_DIRECTION_INVALID: 'TRANSITION_DIRECTION_INVALID',
  TRANSITION_CONDITION_EMPTY: 'TRANSITION_CONDITION_EMPTY',
  TRANSITION_BLOCKING_HARDCODED: 'TRANSITION_BLOCKING_HARDCODED',
  CONTAINER_REFERENCE_INVALID: 'CONTAINER_REFERENCE_INVALID',
  CONTAINER_STRUCTURE_OVERRIDE: 'CONTAINER_STRUCTURE_OVERRIDE',
  EQUIPMENT_SLOT_REFERENCE_INVALID: 'EQUIPMENT_SLOT_REFERENCE_INVALID',
  CONSUMPTION_POINT_REFERENCE_INVALID: 'CONSUMPTION_POINT_REFERENCE_INVALID',
  ATTACHMENT_POINT_REFERENCE_INVALID: 'ATTACHMENT_POINT_REFERENCE_INVALID',
  ITEM_CONVERSION_HARDCODED: 'ITEM_CONVERSION_HARDCODED',
  VEHICLE_SEAT_REFERENCE_INVALID: 'VEHICLE_SEAT_REFERENCE_INVALID',
  VEHICLE_CARGO_REFERENCE_INVALID: 'VEHICLE_CARGO_REFERENCE_INVALID',
  VEHICLE_DOOR_REFERENCE_INVALID: 'VEHICLE_DOOR_REFERENCE_INVALID',
  VEHICLE_ADJACENCY_REFERENCE_INVALID: 'VEHICLE_ADJACENCY_REFERENCE_INVALID',
  VEHICLE_LOCKING_HARDCODED: 'VEHICLE_LOCKING_HARDCODED',
  VEHICLE_DRIVER_SLOT_INVALID: 'VEHICLE_DRIVER_SLOT_INVALID',
  VEHICLE_COLLISION_HARDCODED: 'VEHICLE_COLLISION_HARDCODED',
  VEHICLE_DESTRUCTION_HARDCODED: 'VEHICLE_DESTRUCTION_HARDCODED',
  CONTAINER_CAPABILITY_REFERENCE_INVALID: 'CONTAINER_CAPABILITY_REFERENCE_INVALID',
  CONTAINER_CAPABILITY_OVERRIDE: 'CONTAINER_CAPABILITY_OVERRIDE',
  SLOT_CAPABILITY_REFERENCE_INVALID: 'SLOT_CAPABILITY_REFERENCE_INVALID',
  CONTAINER_CAPABILITY_BINDING_OVERRIDE: 'CONTAINER_CAPABILITY_BINDING_OVERRIDE',

  // ── 运行时提交与投影（Requirements 6、10、13、14） ─────────────────
  RUNTIME_ACTION_UNRESOLVED: 'RUNTIME_ACTION_UNRESOLVED',
  RUNTIME_ACTION_UNAVAILABLE: 'RUNTIME_ACTION_UNAVAILABLE',
  RUNTIME_PRECONDITION_FAILED: 'RUNTIME_PRECONDITION_FAILED',
  RUNTIME_GATEWAY_CONDITION_FAILED: 'RUNTIME_GATEWAY_CONDITION_FAILED',
  RUNTIME_TARGET_OUT_OF_SCOPE: 'RUNTIME_TARGET_OUT_OF_SCOPE',
  RUNTIME_HOOK_INTEGRATION_UNAVAILABLE: 'RUNTIME_HOOK_INTEGRATION_UNAVAILABLE',
  RUNTIME_L1_INVARIANT_VIOLATION: 'RUNTIME_L1_INVARIANT_VIOLATION',
  RUNTIME_TRANSACTION_ABORTED: 'RUNTIME_TRANSACTION_ABORTED',
  RUNTIME_OP_MAPPING_MISSING: 'RUNTIME_OP_MAPPING_MISSING',
  PROJECTION_WRITE_REJECTED: 'PROJECTION_WRITE_REJECTED',
  PROJECTION_SCOPE_VIOLATION: 'PROJECTION_SCOPE_VIOLATION',
  UI_UNKNOWN_RESOURCE_ROLE: 'UI_UNKNOWN_RESOURCE_ROLE',
  UI_DESCRIPTOR_TARGET_UNRESOLVED: 'UI_DESCRIPTOR_TARGET_UNRESOLVED',

  // ── ECS 收敛：原子 System 接线（Requirements 3、5；diagnostic-projection 见 D-ECS-001） ──
  SYSTEM_BINDING_MALFORMED: 'SYSTEM_BINDING_MALFORMED',
  SYSTEM_BINDING_MISSING_KERNELOPS: 'SYSTEM_BINDING_MISSING_KERNELOPS',
  SYSTEM_BINDING_MISSING_FAMILY: 'SYSTEM_BINDING_MISSING_FAMILY',
  COMPOSITION_KIND_NOT_DECLARED: 'COMPOSITION_KIND_NOT_DECLARED',
  COMPOSITION_KIND_INVALID: 'COMPOSITION_KIND_INVALID',
  COMPONENT_ID_CONFLICT: 'COMPONENT_ID_CONFLICT',
  MISSING_CAPABILITY_FOR_COMPOSE: 'missing-capability-for-compose',
} as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];

/** 全部代码的规范化有序列表，供回归夹具与目录完整性测试使用。 */
export const ALL_DIAGNOSTIC_CODES: readonly DiagnosticCode[] = Object.freeze(
  (Object.values(DIAGNOSTIC_CODES) as DiagnosticCode[]).slice().sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)),
);
